[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulex = { version = "0.1.0", path = "../rulex-lib" }
criterion = "0.3.5"

[[bench]]
# run benchmarks with `cargo criterion -p rulex`
name = "main"
harness = false
