[workspace]
members = [
    "./pomsky-lib",
    "./pomsky-syntax",
    "./pomsky-bin",
    "./pomsky-macro",
    "./benchmark",
]
default-members = ["./pomsky-bin", "./pomsky-lib", "./pomsky-syntax"]
resolver = "2"

[profile.release]
lto = "thin"
opt-level = "z"
strip = true
