[package]
name = "rulex"
description = "A new regular expression language"
version = "0.1.0"
edition = "2021"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["dbg"]
dbg = []

[dependencies]
thiserror = "1.0.30"
logos = "0.12.0"
nom = "7.1.0"

[dev-dependencies]
criterion = "0.3.5"
atty = "0.2.14"

[[bench]]
# run benchmarks with `cargo criterion -p rulex`
name = "benchmark"
harness = false

[[test]]
name = "it"
path = "./tests/testcases.rs"
harness = false
