[book]
title = "Rulex"
authors = ["Ludwig Stecher"]
language = "en"
multilingual = false
src = "src"
edit-url-template = "https://github.com/Aloso/rulex/tree/main/book/{path}?mode=edit"

[rust]
edition = "2021"

[output.html]
cname = "aloso.github.io"
site-url = "/rulex/"
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["theme/custom.css"]
additional-js = ["javascript/highlightjs-rulex-regex.js"]
git-repository-url = "https://github.com/Aloso/rulex"
git-repository-icon = "fa-github"

[preprocessor.inline-hl]
command = "node ./book/javascript/preprocessor-inline-hl.js"
